### ISSUE TITLE
 Error Code = 126 

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#15]
Need to add this to the releases page.

if you see this in your Log.txt file

Resources/plugins/DaraRefTool/win.xpl : Error Code = 126 : The specified module could not be found.

Make sure you have installed Visual Studio 2013 Visual C++ Redistributable Package

Found at https://www.microsof...s.aspx?id=40784

**Comment by leecbaker** [comment]
Good call, will add that to the README.

**Comment by leecbaker** [comment]
I've added this to the bottom of the release notes, as it's right above the download link for binaries. I think this will give people the best chance of seeing it before downloading the plugin.
