### ISSUE TITLE
Arrays display incorrect values when elements other than the first one change

### ISSUE THREAD

**Issue by leecbaker** [leecbaker/datareftool#16]
Array support is incomplete in DRT, and may show wrong values. For example, in sim/cockpit/g430/g430_nav_com_sel, the values displayed in DRT aren't updated when the second element (i.e., array[1]) changes. This means the displayed value is incorrect.

DRE shows the correct values in this case.

Thanks to Russ for reporting this problem.

**Comment by durian** [comment]
Has this been solved yet?

**Comment by leecbaker** [comment]
I had a brief look at it and couldn't figure it out. It will be a couple weeks until I have time to dig into it.

Feel free to take a swing at it.

**Comment by leecbaker** [comment]
Fixed in 058dfe9c3d84d44b939263438cfd091e24dd3421 , along with improved tracking of changes. As far as I know, there are no further bugs with arrays (other than that they continue to be read only).
