### ISSUE TITLE
Windows Build not happy.

### ISSUE THREAD

**Issue by TronicLabs** [leecbaker/datareftool#17]
I could not create a working version in windows - visual studio 2013.

Boost library version taken from here:
hxxp://sourceforge.net/projects/boost/files/boost-binaries/1.58.0/boost_1_58_0-msvc-12.0-64.exe/download.

The first error that gives me vs2013 is relative to this line:
https://github.com/leecbaker/datareftool/blob/master/src/find_datarefs_in_files.cpp#L141
does not return a correct conversion,
although setting it to `.string ()` it compiles the plugin,
but running I get a runtime error.

some advice?

**Comment by leecbaker** [comment]
Sorry, I don't have a Windows machine with me at the moment. Perhaps another user can help?

What's the runtime error?

**Comment by leecbaker** [comment]
Sparker provided a build log here- it will be a few days before I have time to look at it.

http://forums.x-plane.org/index.php?showtopic=82960&p=954581

**Comment by leecbaker** [comment]
I've got a windows build working on Appveyor using VS 2015 after fixing a few bugs. You might be able to compare your results against the build log.

https://ci.appveyor.com/project/leecbaker/datareftool

@TronicLabs Let me know if you get it working- I'll close this issue if I haven't heard back in a week or two.

**Comment by TronicLabs** [comment]
thanks I'll try and let you know

**Comment by leecbaker** [comment]
Closing, since we haven't heard back.

**Comment by TronicLabs** [comment]
I'm sorry if I answer only now, but I've been very busy.
I'm testing this with MSVC 2013 - Windows 10, I had to change the constexpr https://github.com/leecbaker/datareftool/blob/master/src/datarefs.cpp#L29-L30 to normal const, MSVC 2013 does not support it, now it compiles without errors, but remains a strange problem, it only works if there are no other active plugins, at least here with my configuration, in particular with the ExtPlane plugins it crashes when trying to open the window, but it works well without.
anyway thanks for your attention.

**Comment by leecbaker** [comment]
@TronicLabs Can you see if it works now?

Also, can you open a separate bug for the Extplane problem?

**Comment by sparker256** [comment]
Builds fine using VS2013 and also gets along with other plugins in X-Plane 10.41r3. It does not like to stop because it will crash X-Plane on shutdown. It works fine on my Ubuntu 14.04 LTS build. Tried to attach Log.txt file but I do not have permission,

--=={This application has crashed because of the plugin: DataRef Tool}==--

Bill

**Comment by TronicLabs** [comment]
New build...
without ExtPlane...
when xplane is closed it crash and in the Log.txt:
--=={This application has crashed because of the plugin: DataRef Tool}==--

with ExtPlane, now the windows is showed, but still crash xplane.

**Comment by leecbaker** [comment]
@sparker256 @TronicLabs I don't have a windows machine, but is there any chance you can get a backtrace?

**Comment by TronicLabs** [comment]
your implementation of datareftool.json preference not have an right path on windows?
It generate some error when close xplane.

sim/flightmodel/engine/POINT_max_TRQ = is an infinite big number?

trying to debug:
First-chance exception at 0x00007FFE8B31A1C8 in X-Plane.exe: Microsoft C++ exception: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure> > at memory location 0x0000000000B8C198.
Critical error detected c0000374

**Comment by leecbaker** [comment]
I think I found the problem- I left in some debug code that tried to write to /tmp/windows.txt, and then caused an exception to be thrown which wasn't caught. I've remedied both of those problems. Can you see what you get now?

**Comment by sparker256** [comment]
Built on all three platforms and did not see any issues in X-Plane running or shutting down. Might be a good time for another release if no other issues show up.

**Comment by TronicLabs** [comment]
It seems to cause an error in the heap memory.

BUILD OUTPUT:
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
1>  Checking Build System
1>  CMake does not need to re-run because E:/XPLANE_DEV/Github/datareftool/build/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/XPLANE_DEV/Github/datareftool/build/src/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: plugin, Configuration: Debug x64 ------
2>  Building Custom Rule E:/XPLANE_DEV/Github/datareftool/src/CMakeLists.txt
2>  CMake does not need to re-run because E:\XPLANE_DEV\Github\datareftool\build\src\CMakeFiles\generate.stamp is up-to-date.
2>  about_window.cpp
2>  clipboard_win.cpp
2>  datarefs.cpp
2>  find_datarefs_in_files.cpp
2>C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility(2132): warning C4996: 'std::_Copy_impl': Function call with parameters that may be unsafe - this call relies on the caller to check that the passed values are correct. To disable this warning, use -D_SCL_SECURE_NO_WARNINGS. See documentation on how to use Visual C++ 'Checked Iterators'
2>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\xutility(2113) : see declaration of 'std::_Copy_impl'
2>          E:\XPLANE_DEV\boost_1_58_0_v12\boost/algorithm/string/detail/classification.hpp(102) : see reference to function template instantiation '_OutIt std::copy<const char*,char*>(_InIt,_InIt,_OutIt)' being compiled
2>          with
2>          [
2>              _OutIt=char *
2>  ,            _InIt=const char *
2>          ]
2>          E:\XPLANE_DEV\boost_1_58_0_v12\boost/algorithm/string/classification.hpp(206) : see reference to function template instantiation 'boost::algorithm::detail::is_any_ofF<char>::is_any_ofF<boost::iterator_range<const char *>>(const RangeT &)' being compiled
2>          with
2>          [
2>              RangeT=boost::iterator_range<const char *>
2>          ]
2>          E:\XPLANE_DEV\boost_1_58_0_v12\boost/algorithm/string/classification.hpp(206) : see reference to function template instantiation 'boost::algorithm::detail::is_any_ofF<char>::is_any_ofF<boost::iterator_range<const char *>>(const RangeT &)' being compiled
2>          with
2>          [
2>              RangeT=boost::iterator_range<const char *>
2>          ]
2>          E:\XPLANE_DEV\Github\datareftool\src\find_datarefs_in_files.cpp(85) : see reference to function template instantiation 'boost::algorithm::detail::is_any_ofF<char> boost::algorithm::is_any_of<const char[6]>(RangeT (&))' being compiled
2>          with
2>          [
2>              RangeT=const char [6]
2>          ]
2>  plugin.cpp
2>  prefs.cpp
2>  viewer_window.cpp
2>  Generating Code...
2>     Creating library E:/XPLANE_DEV/Github/datareftool/build/src/Debug/win.xpl.lib and object E:/XPLANE_DEV/Github/datareftool/build/src/Debug/win.xpl.exp
2>  plugin.vcxproj -> E:\XPLANE_DEV\Github\datareftool\bin\datareftool\Debug\win.xpl
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

Debug Assertion Failed!
File: ..\vctools\crt\crtw32\convert\isctype.c
Line: 56
Expression: c >= -1 && c <= 255

find_datarefs_in_files.cpp
Line: 17

**Comment by leecbaker** [comment]
@TronicLabs thanks for the update. I think I might have fixed it, but it's hard to tell.

I *think* the bug was actually the assertion mentioned at the bottom- use of std::isalnum(). The way I used it could cause invalid input to the function on systems where **char** is signed. This would explain why it didn't present itself on Mac or Linux.

Did you have another reason you suspect memory corruption?

**Comment by TronicLabs** [comment]
I also think so.
maybe you could use a boost regex for the binary parse?

**Comment by leecbaker** [comment]
@TronicLabs Interesting idea, but I'm concerned about the performance implications of that.

Did this fix your bug? https://github.com/leecbaker/datareftool/commit/9f2dafa1401731bc33d81b8390074f89c9eec982

**Comment by leecbaker** [comment]
Closing this task, since I've got a working build now and haven't heard back from the reporter in a while. @TronicLabs feel free to reopen this if necessary.
