### ISSUE TITLE
Missing searching for LUA scripts for xlua in XP11

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#19]
We are not searching for the LUA scripts that xlua can create in aircraft directory. Here is a diff file of what is working for me on my local build.

Bill

[xlua.diff.zip](https://github.com/leecbaker/datareftool/files/706515/xlua.diff.zip)

**Comment by leecbaker** [comment]
Thanks Bill, I'll have a look.

**Comment by leecbaker** [comment]
This should be solved in a commit yesterday, and released in binaries today.
