### ISSUE TITLE
Would it be possible to export the shown Datarefs?

### ISSUE THREAD

**Issue by EinPinsel** [leecbaker/datareftool#21]
Hi, 
we're currently trying to create a Smart-Co-Pilot-Config for a plane and there are over 9000 Buttons to configure. Would it be possible to dump all of the current datarefs into a file or the clipboard? Or maybe only the shown (and therefore filtered) datarefs? 

Thanks in advance :)

**Comment by sparker256** [comment]
Look in Output/preferences/drt_last_run_datarefs.txt
Bill

**Comment by EinPinsel** [comment]
Oh. Ooh! Thanks.
