### ISSUE TITLE
drt_last_run_commandrefs.txt not created

### ISSUE THREAD

**Issue by jockeyboy** [leecbaker/datareftool#22]
As per release notes :  

Release on June 14, 2017
@leecbaker leecbaker released this on 14 Jun

Features:
All known commands and datarefs are listed in Output/preferences/drt_last_run_datarefs.txt and drt_last_run_commandrefs.txt

it does not create drt_last_run_commandrefs.txt
drt_last_run_datarefs.txt  works fine
This is a really useful function for users of spad.next and increases the productivity of creating profiles

**Comment by leecbaker** [comment]
I just had a look, and this does occur on the latest release. Might be a couple of days before I can get to it.

Just curious, how are you using this list? Did you know you can copy and paste dataref / commandref names out of DRT?

**Comment by jockeyboy** [comment]
I use Spad.next to control Saitek Panels it only has access to the Default Xplane datarefs & Commands , unless you add a commands.txt and a datarefs.txt  file into the Aircraft directory , Spad.next will read this and give you access to edit those values or send those Commands. 
With your Last_run  files I can quickly add custom datarefs & commands to Spad.next   rather than copy from the DRT itself. 
So its a very useful feature , as it then saves me having Xplane running and swapping windows while I create a profile.

**Comment by leecbaker** [comment]
This should be fixed in the release I just made: https://github.com/leecbaker/datareftool/releases/tag/2017.11.07

Let me know if it isn't.

**Comment by jockeyboy** [comment]
Works A TREAT!!   Thank you !

**Comment by leecbaker** [comment]
Perfect.
