### ISSUE TITLE
XP11 Default B747-400 Dataref: sim/cockpit(2)/electrical/generator_on[0] not set

### ISSUE THREAD

**Issue by Delufae** [leecbaker/datareftool#24]
Hi there,

I am not sure, if I am right here, but I have noticed, that the mentioned Datarefs (sim/cockpit(2)/electrical/generator_on[0]) dose not change, while the other 3 ([1]-[3]) are set correct when i push the switches (GEN CONT) in the default B747-400 in XP11. can someone explaint how to fix this or is this a bug in the game itself?

Thank you,
Delufae

**Comment by leecbaker** [comment]
I'd recommend posting this in the X-Plane.org forum, as it's not specifically about DRT; however, I expect this is either a bug or limitation of the 747 in X-Plane, and if you take a look at the Lua scripts taht run the plane, you might find your answer. I'd start by looking at the file `X-Plane 11/Aircraft/Laminar Research/Boeing B747-400/plugins/xlua/scripts/B747.03.electrical/B747.03.electrical.lua`
