### ISSUE TITLE
DRT deleting changed dataref

### ISSUE THREAD

**Issue by Forsaken-Player** [leecbaker/datareftool#25]
Before I've updated I used to make a dataref change (with cockpit) and then change the filter to changed recently and dataref would stay there forever. NOW, after it's completely with it disappears... Is this a normal behavior now?

PS: Thank you for this great TOOL!! and sorry for my bad English. :D

**Comment by hansw1204** [comment]
I have exactly the same experience with the last few updates (since about last June). I’m on a Mac, btw.

**Comment by leecbaker** [comment]
This was an intentional change; now I get the idea it was a bad idea. I'll fix this.

**Comment by leecbaker** [comment]
The change is reverted in d85973e6578519ce28b4e339bce5b88452eed2c2. Will be released soon.

**Comment by Forsaken-Player** [comment]
Wow. Super! It's way faster to pin point dataref

**Comment by leecbaker** [comment]
This fix was recently released [here](https://github.com/leecbaker/datareftool/releases/tag/2018.06.06), so I'm going to close this issue.
