### ISSUE TITLE
Gray rectangle at the top of the display

### ISSUE THREAD

**Issue by DrGluck** [leecbaker/datareftool#27]
X-Plane 11.21r2
DataRefTool_2018_05_04

The rectangle disappears when I disable the plugin

![tu-204-100b_1](https://user-images.githubusercontent.com/4846443/40420339-d34ec6e8-5e90-11e8-8f15-32a15fb34311.png)

**Comment by DrGluck** [comment]
Correction: this is the second copy of the plugin window that is outside the screen. This window is open immediately after loading the aircraft.

**Comment by leecbaker** [comment]
This appears to be a DRT window that didn't resize correctly. Try dragging a window border, and it will start rendering correctly.

I am planning on fixing this, I just don't have time this week.

**Comment by leecbaker** [comment]
Windows can no longer overlap the top of the screen. They are automatically moved down if they do. e205d0d428e4eab075d2ce6c77a22ee3a9a33eeb

**Comment by leecbaker** [comment]
Windows also can now be closed by pressing command-w or control-W. These changes will be released soon...
