### ISSUE TITLE
(FR) Make title bar name editable.

### ISSUE THREAD

**Issue by slgoldberg** [leecbaker/datareftool#32]
This is the best tool for X-Plane development; I've used it extensively in building my free plugin I'm about to release and make open-source.  I have saved countless hours thanks to DataRefTool. Thank you.

The biggest productivity feature already there is that DRT auto-saves the open windows between runs and restores them upon startup.  This is so great, I can't even tell you how much I love it! :-) Good job with that.

I may be missing it, but in skimming (admittedly) the code, I don't believe there's any way to customize the title bar text for each window. I see logic for when the user clicks on the title bar text, but I don't see how it lets you change the name (and of course I've tried such multiple ways -- again, if I've missed it and the instructions are clear, I apologize).

If I'm right, though, that brings me to the feature request :-) -- would you be able to add a way to let users do this, and to persist the user-entered per-window title text in the per-window settings you are persisting/restoring between runs?

Also -- and even as a stopgap if the user-entered text is too much work -- a much simpler but equally powerful option would be to simply add the search query to the title bar (truncated as appropriate, of course).

So in that case, I envision the title saying, for example, "DataRef Tool (11): sim/multiplayer/plan..." i.e., where the thing following the count of datarefs shown from the filter, is the actual query text truncated to an appropriate length.

That would at least make it easy for me to tell which of my 7 regular windows that I keep docked down in the bottom of my screen, is which. :-)  But ideally I could label them, like "DataRef Tool (11): Steve's Favorite Query", and have the search query only show up if the user doesn't enter custom text.

Thanks for considering this. I might be willing to help implement it myself, too, but my environment is not quite set up yet for this. I'm not an MS developer, but I've been working on my plugin (which is C-style C++) using MS Visual Studio 2017 community edition, and can build a Win64 plugin from my environment, but that's about it. I tried building in my cygwin environment (this is really another topic isn't it, sorry) and got stumped making it all work, since I really have no clue about how MSBuild works, for example. So .. I can help but I'd probably need some help getting set up for the first time .. if you were willing to invest the time in that, I am happy to try to add this feature myself. It might also help me figure out how to support more than just Win64 for my plugin  (called "ABC") I'm about to release.

Thanks again.

**Comment by leecbaker** [comment]
Hi @slgoldberg,

Fantastic idea. There's no code in there to change the window title right now, but it should be relatively straightforward for me to put search queries in the title. I'll do that.

Custom titles would be quite a bit more work- I'm going to keep that idea in the back of my mind for the future.

For a local build environment, I recommend using CMake-gui.exe to generate a Visual Studio 2017 project. That's what I do. You'll need to have boost static libraries installed- I use vcpkg for that, but it's a bit more complicated.

For release binaries, I've actually got a completely automated build system set up- it uses Appveyor and Travis CI. This way, I don't have to worry about building in exactly the same way each time on 3 platforms- I just develop on Mac, test on Windows, and zip up the binaries that are made automatically.

-Lee

**Comment by leecbaker** [comment]
This has been released.

**Comment by slgoldberg** [comment]
Awesome, Lee! Thank you so much for taking this suggestion!

I am sorry for delay, and hopefully this comment won't reopen this, but I just wanted you to know for some reason I only saw this thread today (my Gmail filters must be defined poorly, since only the last notification message made it into my inbox).

This is really great, thank you again. I'll test it out and let you know if I see any problems. And thanks for the info on building; I'll try that too if/when I have time.  As I've said on the forum, I think this is the most powerful and useful tool for X-Plane development I've ever used, and continues to be. So, thank you again for this!

**Comment by slgoldberg** [comment]
Tested released version (2018_09_19) and it works perfectly! Thanks again.
