### ISSUE TITLE
Rescan Commands

### ISSUE THREAD

**Issue by Clamb94** [leecbaker/datareftool#35]
I'm generating some custom commands using FlyWithLua, but they are not visible in the Datareftool.
Would be great if we could rescan for commands, just like rescaning for Datarefs

**Comment by sparker256** [comment]
If we looked in "Resources/plugins/FlyWithLua/Scripts" for datarefs and commands found in the *.lua files that should help resolve this issue.

**Comment by leecbaker** [comment]
> Would be great if we could rescan for commands, just like rescaning for Datarefs

The rescan for datarefs menu item should actually rescan for datarefs and commands both.

I'll add that path to be scanned.

**Comment by leecbaker** [comment]
Added this functionality in 9eb5fb7c9b2caf0f715d8c1ce840cc1c1be0c906

I'll leave this issue open until somebody can confirm that it actually works.

**Comment by sparker256** [comment]
Did a local build on Linux and is working correctly for both datarefs and commands.

**Comment by leecbaker** [comment]
Closing this issue, as a release has been made
