### ISSUE TITLE
Lots of datareftools stacking on top of each other

### ISSUE THREAD

**Issue by SimInnovations** [leecbaker/datareftool#36]
Since the latest version a lot of datareftool windows stack on top of each other. Each time I open a new one, the next X-Plane session starts, there's a new one on top. Disabling the datareftool removes then, but enabling it brings them back. Screenshot: https://www.dropbox.com/s/f9tqwptr59kwk2h/datareftoolstack.jpg?dl=0
If I remove the plugin and replace it with a new one, they're still there.

**Comment by leecbaker** [comment]
Interesting. I haven't seen this myself- I'll take a closer look soon.

**Comment by leecbaker** [comment]
Hi @SimInnovations , can you see if this is still happening with the latest version of DRT?

**Comment by SimInnovations** [comment]
Will do! Thanks for the notification.

**Comment by SimInnovations** [comment]
This issue was fixed. Thanks!

**Comment by leecbaker** [comment]
Cool.
