### ISSUE TITLE
With the latest commit if you make the view window to small on Linux you get CTD.

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#37]
When testing the new FlyWithLua search I found that if I make the view window small enough that no test was displayed I will get a CTD.

Also in looking at the Log.txt file there seems to be a small formatting issue where some of the "Found XX" is not prefaced with "DataRefTool: "
 
[DataRefTool_GDB_TerminalDump_WindowToSmall.txt](https://github.com/leecbaker/datareftool/files/2591799/DataRefTool_GDB_TerminalDump_WindowToSmall.txt)
[Log.txt](https://github.com/leecbaker/datareftool/files/2591800/Log.txt)

**Comment by leecbaker** [comment]
Thanks Bill, I expect to fix this today.

**Comment by leecbaker** [comment]
This fix is included in the current release. This bug in particular is fixed with 02504951cd97b810d877b96bf3460cd3407ae6c2
