### ISSUE TITLE
[Feature request] Option to make the font bigger

### ISSUE THREAD

**Issue by Danita** [leecbaker/datareftool#38]
It would be nice to have an option for font size, sometimes is difficult to hit the targets with the mouse cursor and it would help improve readability too. Thanks again for this wonderful tool!

**Comment by leecbaker** [comment]
Hi @Danita, unfortunately, X-Plane's text rendering APIs only support one font size. It's really too bad- I hope they add more flexibility in the future.

**Comment by Danita** [comment]
Thanks!
