### ISSUE TITLE
Some datarefs are not writable

### ISSUE THREAD

**Issue by HellGL** [leecbaker/datareftool#39]
Sometimes I encounter datarefs which are supposed to be writable (according to DataRefs.txt) but I can only delete an old value but not enter a new one. Example:
`sim/joystick/joystick_axis_assignments	int[500]	y	enums	Assignments for the joystick axes - what does X-Plane think each one is? [Was 15 before 850][Was 24 before 860][was 32 before 900]`
In DataRef Editor I can change the value and DRT immediately change the color of the entry due to the changed value. But if I try to enter something in DRT I am only able to delete the value in the array, but not change it.

**Comment by leecbaker** [comment]
I totally see what you're talking about here- let me see what I can do.

**Comment by leecbaker** [comment]
I'm pretty sure this has something to do with array datarefs that have many items. I *think* what is happening is that the edit text box has so much text in it, that X-Plane has decided to not let you enter an more text until some is deleted.

So, for now, it looks like you can't edit these long datarefs.

**Comment by leecbaker** [comment]
Closing the issue, as there's simply not a good fix available for now.
