### ISSUE TITLE
Duplicate Dataref Registration

### ISSUE THREAD

**Issue by benrussell** [leecbaker/datareftool#4]
Plugin will accept multiple plugin registration messages and add all items to the pool of known datarefe names.

This results in duplicate items being displayed.

This can build up to annoying levels over multiple hours of development.

Suggest adding either loop scanning code or a secondary std::map<string,int> check to detect multiple items being added.

Worth noting that DRE has been reported to get quite slow when developing large commercial products and registering hundreds of custom datarefs. 

Speed is an important consideration for any fix for this issue.

**Comment by leecbaker** [comment]
Interesting. I'll have a look at this.

**Comment by leecbaker** [comment]
I've confirmed that datareftool does have a problem with accepting duplicate dataref registrations. I will be fixing this soon.

**Comment by leecbaker** [comment]
@benrussell I believe I have a fix for this issue committed. Let me know if you're still having an issue.
