### ISSUE TITLE
Window changes position after reloading X-Plane

### ISSUE THREAD

**Issue by Danita** [leecbaker/datareftool#42]
I have set up X-Plane in windowed mode. It always opens in a smallish window which once has finished loading I maximize. With this setup:

1. Open a DRT window and place it on the center of the screen.
2. Close X-Plane
3. Open X-Plane and maximize it again.

The DRT window doesn't remember its position and appears overlapping X-Plane's menu bar area and you have to click the window border in order to be able to reposition it or close it.

**Comment by leecbaker** [comment]
I'll have a look at this.

For a while, I've planned to move to the new XPLM version 3 window APIs, which solve some of the problems with windows and the border of the screen. In the meantime, I'll try to improve how the windows interact with the window borders.

**Comment by SimInnovations** [comment]
I also see this quite often. It's easy to solve by double clicking on the edge of the window, that brings it back in view.

**Comment by leecbaker** [comment]
@SimInnovations  which version are you running? Can you test this version, and see if it fixes the problem? I think I've made some significant improvements in this area. https://github.com/leecbaker/datareftool/actions/runs/53371697

**Comment by SimInnovations** [comment]
I am running the version from 2019-12-04, the latest one published here: https://github.com/leecbaker/datareftool/releases
Is that an older version?

**Comment by SimInnovations** [comment]
I've just tried the version you posted, the issue is still there.
![image](https://user-images.githubusercontent.com/11886104/76683379-ee780700-6603-11ea-819c-3312de3297ce.png)

**Comment by leecbaker** [comment]
That is the latest development build, it's from 4 days ago. I wonder why on earth the window is positioned there. Do you have multiple monitors?

**Comment by SimInnovations** [comment]
No sorry, this was on a all-in-one desktop PC, but it happens at my laptop and work PC as well.

**Comment by leecbaker** [comment]
@SimInnovations thanks for the information.

**Comment by leecbaker** [comment]
Hi @Danita and @SimInnovations,

I've recently re-written the UI of DataRefTool to use the XP11 style windows. I *think* this should keep all of your windows on screen, and I expect the issue with windows overlapping the X-Plane menu have been completely resolved. You can download the new version [on this page](https://github.com/leecbaker/datareftool/releases).

If I'm wrong and this issue still persists, please re-open this issue and let me know.

-Lee

**Comment by Danita** [comment]
@leecbaker Thanks for this amazing update. The problem still somewhat persists (the window is partially obscured after x-plane loads) but if I maximize the window again, DRT moves back to the last used position, so it's not as annoying as before :-P

The new design is better as well, but I'd suggest giving the content window a bit of padding (the text is too close to the edges) and left-align the numbers again for better scannability. Also we lost the ability to double click to edit-in-place, so now it takes a lot more steps to edit a value (clic dref, move mouse, click Edit, move mouse, click to focus on field).

Love the way you can keep a dataref always visible, though.
