### ISSUE TITLE
where to place datareftool in xplane 11

### ISSUE THREAD

**Issue by jefken153** [leecbaker/datareftool#46]
I have a question regarding the use of Create Dictionary.
It says that xcheckdisk needs a data tool to download at github.com which I did.
Now my question is where should I put DataRefTool_2018_11_18 somewhere. In which directory

**Comment by leecbaker** [comment]
To install DRT, put the folder you download inside `X-Plane 11/Resources/plugins`. When done correctly, you should see the DataRefTool submenu in the plugins menu in X-Plane.
