### ISSUE TITLE
About Box Should be Wider

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#52]
The url text is wider than the about box.
![AboutBoxWidth](https://user-images.githubusercontent.com/1274225/67939716-88389d80-fba8-11e9-9b2e-bfe69d6471bb.jpg)

**Comment by leecbaker** [comment]
Good catch.

**Comment by leecbaker** [comment]
Fixed in 69ee261b6777e1a6cb44153bd00654e3007a7ae5
