### ISSUE TITLE
data datarefs are RO

### ISSUE THREAD

**Issue by nmeier** [leecbaker/datareftool#54]
It seems that datarefs of type data are modelled ([isData](https://github.com/leecbaker/datareftool/blob/cd2278d14e3a0edd644abd4920ca132626566f61/src/lib/dataref.h#L50)) but one can't edit them even if they're editable through X-Plane, example

sim/aircraft/view/acf_tailnum

Would be good to allow for data values to be edited (string to number array).

**Comment by leecbaker** [comment]
Sounds good. I skipped this initially because I figured nobody uses this feature. I've decided to implement it now.

**Comment by leecbaker** [comment]
@nmeier I have implemented this feature. It will be in the next release of DRT.

![image](https://user-images.githubusercontent.com/1047159/70095397-81121d00-1689-11ea-825e-2527e43846a8.png)
