### ISSUE TITLE
Some (Plugin) DataRefs missing

### ISSUE THREAD

**Issue by Mazn1191** [leecbaker/datareftool#55]
I'm having the problem with a bunch of DataRefs that I'm seeing in the DRE but not in the DRT.

Those are DataRefs of an addon aircraft (Carenado B200) which uses a long array "com/dkmp/BT3" to control buttons in the cockpit.

Not sure if there's anything that can be done about it, since it might be that the Carenado B200 in this case is communicating the DataRefs directly to the DRE so DRT doesn't have a chance to get those?

Edit: Enabling "Impersonate DRE" and uninstalling DRE did the trick. All datarefs now show up. Not sure if there are any downsides to impersonating DRE.

**Comment by sparker256** [comment]
Do you have Impersonate DRE enabled?

![Impersonate_DRE](https://user-images.githubusercontent.com/1274225/70865365-b8ef4f00-1f2a-11ea-89db-13813ff672b3.jpg)

**Comment by cpuwolf** [comment]
Thanks to "Impersonate DRE"

**Comment by leecbaker** [comment]
Sounds like this issue is solved, so I'm going to close it.

Perhaps in the future, "Impersonate DRE" should be on by default.
