### ISSUE TITLE
Toggle DRT verbosity on/off

### ISSUE THREAD

**Issue by airfightergr** [leecbaker/datareftool#56]
As developer, many times I will look in Log.txt file for my debugging, but DatarefTool adds a lot of lines to the file, that makes searching for my lines a bit hard.

An option to turn datareftool's output into Log.txt file on or off will be great.

**Comment by leecbaker** [comment]
That sounds like a good idea, but unfortunately it isn't very high on my priority list for now.

I'll consider adding a "debug mode" in the future.

**Comment by leecbaker** [comment]
I've gotten some more requests for this- expect some changes in this area in the near future.

**Comment by leecbaker** [comment]
Implemented as part of the new logging system in 14a9633adab3ffecc7c0d6133bc3a26d46feea59
