### ISSUE TITLE
Build failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by danapple0** [leecbaker/datareftool#58]
```
$ uname -a
Linux wotke.danapple.com 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ mkdir build && cd build && cmake .. && make
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
```
[ ... bunch of good stuff happens ...]
```
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libboost_filesystem.a(operations.o): relocation R_X86_64_PC32 against symbol `_ZN5boost10filesystem16filesystem_errorC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKNS0_4pathESC_NS_6system10error_codeE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/plugin.dir/build.make:337: recipe for target '../bin/datareftool/lin.xpl' failed
make[2]: *** [../bin/datareftool/lin.xpl] Error 1
CMakeFiles/Makefile2:261: recipe for target 'src/CMakeFiles/plugin.dir/all' failed
make[1]: *** [src/CMakeFiles/plugin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by leecbaker** [comment]
You need to recompile boost with `-fPIC` like the error message says. It's a real pain that you can't use the version in the package manager.

DRT releases are built on 18.04 right now, using [these commands](https://github.com/leecbaker/datareftool/blob/master/.github/workflows/build.yml#L41-L49) on Github actions.

Feel free to open the issue again if you encounter other errors, but I'm fairly certain that following those commands will work for you.

**Comment by danapple0** [comment]
I didn't realize that it was a boost-specific recompilation that is required.  I'll give it a shot.  Thanks!

**Comment by leecbaker** [comment]
On Linux, any library that is statically linked into a dynamic library (like an XPL) must be compiled with -fPIC. It took me a while to figure this out.
