### ISSUE TITLE
Linux clipboard support

### ISSUE THREAD

**Issue by jason-watkins** [leecbaker/datareftool#6]
I've come up with a basic implementation for `getClipboard` on Linux (available [here](https://github.com/jason-watkins/datareftool/blob/master/src/clipboard_linux.cpp)), but I'm not sure how best to proceed with `setClipboard`.

The way the X11 "clipboard" works, the plugin is responsible for actually serving up the content at the time the user tries to paste into another application. This means that the copy functionality will need to either spawn a daemon to handle requests, or integrate a flight loop callback to check for and service requests. Both options seem messy to me; can anyone suggest a third route?

**Comment by benrussell** [comment]
http://linux.die.net/man/1/xclip ?

**Comment by jason-watkins** [comment]
@benrussell: Possibly a much more elegant solution to both functions, but `xclip` doesn't appear to be installed on my Linux dev machine.

**Comment by benrussell** [comment]
Well for my work I plan to depend on xclip and use some kind of graceful fallback.

As far as linux work arounds go asking people to install xclip is pretty trivial. 

The current state of affairs is (and has been for quite some time) a horrible mess of weird broken ABI's and version numbers.

Ubuntu 15.04 has just started to gain uptake and we're seeing the same boring problems all over again.
(Some obscure package name I can't remember got an update for most system components, X-Plane and it's associated bits require that the user track down the exact matching earlier version and install it by hand...)


The existing situation in the field is anything but ideal. :)

**Comment by leecbaker** [comment]
Added in 359fa17. I don't have the means to test this, but it compiled fine once I installed the libx11-dev package. Feel free to reopen this issue or create another if there is more work that you linux guys want to do on copy/paste support.
