### ISSUE TITLE
Can't enable the DRT

### ISSUE THREAD

**Issue by maarek** [leecbaker/datareftool#61]
I am having an issue where the DRT won't enable. It loads up in the sim and loads disabled. When I try to enable it and change pages or close out of the plugin manager, the DRT is still disabled and the menu items are unselectable. 

The logs do not mention anything about it being disabled or errored. They are full of the `Found n unique possible datarefs...`.

XPlane 11.41r1
DRT from 3/23

**Comment by maarek** [comment]
It seems to have resolved itself out of the blue. Close if you think it's unimportant.

**Comment by leecbaker** [comment]
Did you have DataRefEditor installed as well? If you have DRE installed, and DRT is in "impersonate DRE" mode, that may cause a problem like this.

I'm going to close this issue since you seem to have it resolved. If it reoccurs, feel free to re-open the issue and post or email me your Log.txt.
