### ISSUE TITLE
Symbol not found with X-Plane 10.51r2 and 2020_03_23 releae

### ISSUE THREAD

**Issue by marcelobartsch** [leecbaker/datareftool#62]
dlerror:dlopen(/X-Plane 10/Resources/plugins/DataRefTool_2020_03_23/mac.xpl, 6): Symbol not found: _XPGetWidgetUnderlyingWindow
  Referenced from: /X-Plane 10/Resources/plugins/DataRefTool_2020_03_23/mac.xpl
  Expected in: /X-Plane 10/Resources/plugins/XPWidgets.framework/XPWidgets
 in /X-Plane 10/Resources/plugins/DataRefTool_2020_03_23/mac.xpl

**Comment by leecbaker** [comment]
Current versions of DRT only support X-Plane 11.

This should be the final version to support X-Plane 10: https://github.com/leecbaker/datareftool/releases/tag/2018.04.14

**Comment by leecbaker** [comment]
Closing, since I think this problem is resolved.
