### ISSUE TITLE
New X-Plane Gui style

### ISSUE THREAD

**Issue by airfightergr** [leecbaker/datareftool#63]
It will be awesome if you move DRT to the new GUI, since it can be more readable and can be popped out to a second display.

**Comment by leecbaker** [comment]
I'm working on it, and I think a beta version with this capability should be out in the next couple of weeks. Quite a bit has changed in the new UI, and I think it's quite a bit better.

Here's a preview.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/1047159/99911821-80203400-2cbc-11eb-88a9-1e91fd295695.png">

**Comment by leecbaker** [comment]
Hi @airfightergr ,

I've released a new version of DRT using the new GUI style, with popout windows and all the other XP11 features. I hope you enjoy it!

You can download the latest release here:
https://github.com/leecbaker/datareftool/releases/tag/2021.01.25
