### ISSUE TITLE
Cant't edit an int dataref array of 256

### ISSUE THREAD

**Issue by markcellis** [leecbaker/datareftool#64]
I have a dataref int array that was originally 50 ints. The dataref tool had no problems allowing me to edit individual elements. I changed the array size to 256 and now the dataref tool will not allow entries in the element. It lets put put the cursor on the element and it will accept the backspace to clear it out but it will not take any number input. It is almost acting like to it ro when the dataref is definitely rw.

Note, I only have a 1080P monitor so I can't see all of the 256 elements. I'm not sure if it has something to do that.

**Comment by leecbaker** [comment]
Hi Mark,

I've rewritten the interface for DRT in the past few months, and I think you'll find the process of editing array values greatly improved, especially for bigger arrays. I had no problems editing arrays with mroe than 1000 elements in the new version.

![image](https://user-images.githubusercontent.com/1047159/105813545-9f199b80-5f75-11eb-9e71-c7b3fb0dd207.png)

The latest release can be downloaded [on this page](https://github.com/leecbaker/datareftool/releases/tag/2021.01.25). Hope this helps.

-Lee
