### ISSUE TITLE
Hidden window steals some fps

### ISSUE THREAD

**Issue by DrGluck** [leecbaker/datareftool#65]
Hi! It looks like sometimes there are hidden windows that continue to spend FPS. Judging by the settings file, there are two such windows.
I made a quick video of how to reproduce this. Maybe you should add the "do not open windows at startup" option? Or something like this.

[datareftool.zip](https://github.com/leecbaker/datareftool/files/5056337/datareftool.zip)
[2020-08-11_13-09-03.zip](https://github.com/leecbaker/datareftool/files/5056326/2020-08-11_13-09-03.zip)

**Comment by namarrgon** [comment]
I don't know if this is due to 'hidden windows', a general bug with the plugin or an xplane bug but DRT eats up about a quarter of the frame-time on my system (in vulkan and in opengl mode) even when it's not interacted with and none of its windows are open, which amounts to ~15fps: 

![DRT3](https://user-images.githubusercontent.com/3209906/93625968-09786900-f9e3-11ea-9873-ec902be626ba.png)

![DRT2](https://user-images.githubusercontent.com/3209906/93625040-8f93b000-f9e1-11ea-84cc-b08ad3620f42.png)

**Comment by leecbaker** [comment]
Hi @DrGluck and @namarrgon ,

DRT does take significant CPU time to check the values of datarefs every frame; this is the performance hit that you see. DRT only does this when at least one window is open, so it's totally plausible that the performance loss you're seeing is related to a window being open.

There are some issues where windows in X-Plane get changed to different sizes and moved offscreen. I'm working to fix this in a future version of DRT that will handle windows in an entirely different manner.

Just to make sure that this is a problem with offscreen windows, can you try moving or deleting your DRT preferences file (X-Plane 11/Output/preferences/datareftool.json) and make sure that you don't see any performance cost when using DRT with no windows open?

**Comment by DrGluck** [comment]
As far as I remember, deleting the file solves the problem. So I wrote that the problem is the lost window. I will try to check this later.

**Comment by DrGluck** [comment]
Confirmed. I deleted datareftool.json and now no fps drops. Obviously the problem is in the hidden window.

**Comment by leecbaker** [comment]
@DrGluck Thanks for the confirmation- this should be fixed soon.

**Comment by DrGluck** [comment]
@leecbaker looks like the problem was solved in the last release.
But I seem to have discovered a couple of new bugs. I will research this and create new issues.

**Comment by leecbaker** [comment]
Glad to hear it! I'm going to close this issue since the problem was fixed- please create issues for any problems you encounter.
