### ISSUE TITLE
XP11.50 performance killer

### ISSUE THREAD

**Issue by cpuwolf** [leecbaker/datareftool#67]
when datareftool is on, ~10fps will be killed

**Comment by leecbaker** [comment]
Hi @cpuwolf ,

DRT takes quite a bit of CPU to actually read all the datarefs that it needs to read. This is mostly an unavoidable consequence of how DRT works.

I have written up some tips [on datareftool.com](https://datareftool.com/#faq-datareftool-causes-me-to-loose-fps-why) describing a few things you can try to help performance.

Hope this helps.
