### ISSUE TITLE
Linux memset build issue

### ISSUE THREAD

**Issue by sparker256** [leecbaker/datareftool#7]
I had to move #include cstring from  datarefs.cpp to datarefs.h to build correctly.

Not sure if this change should bother other platforms.

**Comment by sparker256** [comment]
This should have said.
I had to move #include <cstring> from datarefs.cpp to datarefs.h to build correctly.

Not sure if this change should bother other platforms.

**Comment by sparker256** [comment]
This should have said.
I had to move #include "<cstring>" from datarefs.cpp to datarefs.h to build correctly.

Not sure if this change should bother other platforms.

**Comment by leecbaker** [comment]
Fix committed in d0c10b5, thanks for the bug report.
