### ISSUE TITLE
Hotkeys work several times in one click

### ISSUE THREAD

**Issue by DrGluck** [leecbaker/datareftool#76]
Well, hotkeys does not work. Again. Sorry to bring this bad news )

I assigned a key to "Open a new search window". If I make one click on a button, there is a good chance that multiple windows will open. If I hold down the button for a couple of seconds, a lot of windows open.
It is much worse that this bug is present when reloading plugins. The plugins are reloaded several times in a row.

I checked release 2020_03_23, it works fine.

**Comment by leecbaker** [comment]
Hi again,

This should be fixed in the release I made today. I was running into the same issue.

If this doesn't fix the problem for you, please reopen the issue.

https://github.com/leecbaker/datareftool/releases/tag/2011.03.13

-Lee
