### ISSUE TITLE
Can't change sim/time/zulu_time_sec

### ISSUE THREAD

**Issue by soitanen** [leecbaker/datareftool#80]
Using version from 2021-03-13

What I do:
Open DRT main window
Filter zulu word
Click on zulu_time_sec dataref
Press Edit button
Click on bottom current value
Delete it and make new
Press Set button

Nothing happens.

What I expect: changing of ataref value and changing daytime. I remember, that I could change this value when DRT used old interface.

**Comment by leecbaker** [comment]
Hi @soitanen,

I'm not able to replicate this. When I set the zulu time dataref, the time in the simulator changes instantly.

Can you try to replicate this with no other plugins installed to ensure that some plugin isn't overriding the time that you set?

**Comment by leecbaker** [comment]
It's been over a year since this was reported, and I'm unable to replicate this issue. Please re-open if you are still running into it.
