### ISSUE TITLE
Datarefs loaded from aircraft at sim start bypass drt_ignore.txt

### ISSUE THREAD

**Issue by RotationMatrix** [leecbaker/datareftool#81]
I am encountering the issue in #33 and added the crashing dataref to my `drt_ignore.txt`, however DRT still appears to be reading the dataref. My `drt_ignore.txt` ignores other datarefs but not the one which crashes.

In the debugger just before the crash, it appears the dataref is not ignored since it came from an aircraft.

![drt_ignore_debug](https://user-images.githubusercontent.com/52428419/114317076-597c6180-9ad4-11eb-900f-98ca2c7e416e.png)

Please let me know if there is something obvious I've missed.

### Additional Info

X-Plane 11.53r1 on Linux
DataRefTool 2021.03.13 and e24765e5 

`drt_ignore.txt`:
```
B407/Lights/CL1
B407/Lights/CL2
B407/Lights/CL3
sim/airfoils/afl_cd
```

**Comment by RotationMatrix** [comment]
It appears this behaviour only occurs if the aircraft which contains the ignored dataref is loaded at sim start. A workaround is to load another aircraft (default C172) first and then load the aircraft with the ignored dataref.

**Comment by leecbaker** [comment]
Hi @RotationMatrix,

Thanks for the bug report, and for the additional details about the Bell 407 crashing bug. I'd love to get both of these fixed.

The first issue seems to be that the ignore list is loaded potentially after the first aircraft. I expect that will be a relatively easy fix. I'll post again in this thread when I think I have a fix.

-Lee

**Comment by leecbaker** [comment]
Hi @RotationMatrix,

I think I've just fixed this bug. You can get the latest automatically-compiled version of DRT here: https://github.com/leecbaker/datareftool/actions/runs/765890018 Can you confirm that this fixes the issue?

Also, if you can figure out which datarefs are causing the Bell 407 to crash, can you post that in bug #33? Once you post there, I'll put the details on https://datareftool.com for anybody else that's experiencing the bug.

Thanks for your help troubleshooting.

-Lee

**Comment by RotationMatrix** [comment]
Hi @leecbaker 

Awesome! This has fixed the crashing and I can confirm in the debugger that the ignored datarefs are showing as expected now. I'll post the list in #33 for reference.

Thanks for an amazing tool! 😃
