### ISSUE TITLE
Information about "changed" behavior

### ISSUE THREAD

**Issue by devleaks** [leecbaker/datareftool#91]
Hello,
What's the difference between `ch` and `CH` behavior?
Are array flattened? Change criteria more severe?
Please document.
Thank you

**Comment by leecbaker** [comment]
Hi Pierre,

DRT distinguishes between large and small changes; I'm calling a change of less than 1% per frame a "small" change. Imagine things like the outside temperature- it changes, but only very slowly, and very little (as a percentage). There are a ton of datarefs changing very slowly, but they usually aren't what I'm looking for, so I use the "CH" mode- big letters for big changes.

I'm about to put out a new website for datareftool- I'll add some documentation of this feature there.

**Comment by devleaks** [comment]
Thanks. Very handy tool for developer.
In addition of the "amplitude" of the change, one thing you might consider filtering is the frequency of the change. I know you somehow do it through the color of the dataref but I think that it would be handy to optionally exclude datarefs that changes very quickly.
Thank you again for your explanation, I'll report it to plane forum.
Best regards
Pierre

**Comment by jimb39** [comment]
In change mode v 2.30 of dataref tool you can't scroll down to find a changed dataref becuse as soon as something changes it jumps back to the top of the list.
