### ISSUE TITLE
Issue for colour-weak/-blind people in the search-window

### ISSUE THREAD

**Issue by charraeus** [leecbaker/datareftool#92]
Hello Lee,
I'm color-impaired, which means that I can't recognize or distinguish colors - especially red, yellow and green hues - very well (about 8 - 9% of all men are affected). 

**Would it be possible to make the colors of "Command" and "Command (recently used)" on the one hand and the colors of "Dataref" and "Dataref (recently used) on the other hand more distinguishable?**

For example:
* Dataref: white (as is the case now)
* Dataref (recently used): a darker blue (and/or maybe in bold font?)
* Command: yellow (as is the case now)
* Command (recently used): a darker green  (and/or maybe in bold font?)
* And please avoid (dark) red colors on a dark background.

Unfortunately I don't know C/C++, otherwise I would like to do the change myself. 
Thanks a lot, Christian

**Comment by leecbaker** [comment]
Hi Christian,

Thanks for bringing this to my attention; I had not even considered the color choices here, so I took a few minutes to learn what I could do, and I found this a good read: https://davidmathlogic.com/colorblind/

I took a look at the safe color palettes introduced in that post; I've coded up a new color palette based on Wong's figure 2 here: https://www.nature.com/articles/nmeth.1618

Any thoughts on this color scheme? I hope this is better!

This is a screenshot from the newest version of DataRefTool, coming out soon:
![image](https://user-images.githubusercontent.com/1047159/190886599-4910af2c-b55f-4d20-be4c-107909e7d86d.png)


And, here's the code:
```rust
        // Colors from Wong, figure 2
        // https://www.nature.com/articles/nmeth.1618
        let white = color_3f_from_hex(255, 255, 255);
        let wong_orange = color_3f_from_hex(230, 159, 0);
        let wong_sky_blue = color_3f_from_hex(86, 180, 233);
        let wong_yellow = color_3f_from_hex(240, 228, 66);
        let wong_blue = color_3f_from_hex(0, 114, 178);
        let wong_vermillion = color_3f_from_hex(213, 94, 0);
        let wong_reddish_purple = color_3f_from_hex(204, 121, 167);

        let color_dataref = white;
        let color_dataref_small_change = wong_sky_blue;
        let color_dataref_large_change = wong_blue;
        let color_command = wong_yellow;
        let color_command_actuated = wong_orange;
        let color_ignored = wong_reddish_purple;
        let color_deprecated = wong_vermillion;
```

**Comment by charraeus** [comment]
Hi Lee,
Thank you very much for your effort. I am thrilled and look forward to testing the next version :-)
Some feedback to the screenshot:
1. For me it is very hard to distinguish  "Wong_sky_blue" from "Wong_blue"
2. The "depreciated color" on black background is hardly readable
3. All other is perfectly readable for me

Best regards,
Christian

**Comment by leecbaker** [comment]
Hi Christian,

Thanks for your feedback. I do hope this is a big improvement!

1. The difference between datarefs that use the wong blue and sky blue- these were all the same color until last week, so I hope that not being able to distinguish this isn't a major loss. I'm not sure what else to do with the colors to produce something usable. Worst case, the "ch" and "CH" filters can be used to separate large and small changes (as they were in previous versions).
2. Understood. These should be rare; if there's a better color that makes sense, please let me know.
3. Good!

I've put an explanation up for what the colors mean here: https://datareftool.com/#coloring ; hopefully this explanation helps.

I'm going to close this issue, as I hope I've addressed it well enough; if not, feel free to re-open it.
