### ISSUE TITLE
Doesn't work correctly with Toliss A319

### ISSUE THREAD

**Issue by thm-unix** [leecbaker/datareftool#93]
MCDU datarefs are either showing empty string, or corrupted data. Maybe forgot \0 somewhere?

**Comment by thm-unix** [comment]
![image](https://user-images.githubusercontent.com/84270488/193699497-c5f59e9d-83e5-4f7e-8f90-ccf19ff323ca.png)

**Comment by leecbaker** [comment]
> MCDU datarefs are either showing empty string, or corrupted data.

Most of the datarefs that you've shown above appear to be valid text lines from the MCDU. This is something you'd have to bring up with the developer of the aircraft.

DRT reads the content of datarefs, and displays it as best it can. With the "Data"-type datarefs, there is no guarantee that they contain readable text. DRT makes the assumption that the data contained in them is text, and tries to display it with that assumption. It can just as easily be binary data, or really anything.

The contents of the dataref are really up to the developer; DRT can only focus on displaying whatever it gets from the aircraft plugin. Anything beyond that is the responsibility of the developer. If you think there's a better way that these values can be displayed, feel free to re-open this issue.
