### ISSUE TITLE
X-Plane 12

### ISSUE THREAD

**Issue by SimInnovations** [leecbaker/datareftool#94]
Will you be making a version for X-Plane 12? It does work, but it has a few quirks compared to X-Plane 11. Let me know if you want a list of the issues. I also believe that X-Plane 12 comes with a warning the first time you add the datareftool to X-Plane 12, I dont' remember exactly what it was.

**Comment by StamTso** [comment]
It's a bit confusing as there is no information in Github and only a tiny remark on the webpage. Datareftool's active repo is not this one anymore. You can find X-Plane 12 compatible versions on their website https://datareftool.com/download

**Comment by SimInnovations** [comment]
That is good to know. Thank you very much!

**Comment by leecbaker** [comment]
> It's a bit confusing as there is no information in Github

I agree! I've added a note to the top of the repo pointing to the new location.
